### ISSUE TITLE
Please consider logging by default

### ISSUE THREAD

**Issue by mbyio** [KimMachineGun/automemlimit#5] opened 2023-04-23 01:39 UTC
Hey, I just started using this package. I like it! But, I use it alongside automaxprocs, and I noticed automaxprocs always logs when it changes the GOMAXPROCS setting, whereas your package only logs when debug mode is enabled. I think since most people will use both packages, it would be nice if you also logged by default.

**Comment by KimMachineGun** [comment] 2023-04-23 14:27
Hi @mbyio!
Thank you for your proposal.

I'm planning to make some changes to logging in v0.3.0 (using a library like [slog](https://pkg.go.dev/golang.org/x/exp/slog) for structured logging).

It won't log everything by default, but I'm considering increasing the log level of some important logs appropriately to be recorded by default.

**Comment by mbyio** [comment] 2023-04-28 19:23
I think I just want it to log what automaxprocs logs, which is whether or not it changed the memlimit, and, if it did, what it set the memlimit to.

**Comment by thapabishwa-plerionaut** [comment] 2023-11-08 07:22
@KimMachineGun Can I use loggers like klog with this package?

**Comment by KimMachineGun** [comment] 2023-11-08 07:53
@thapabishwa-plerionaut 
I don't know much about the `klog` package. However, I'm currently working on migrating the logging package to `log/slog` (announced in Go 1.21). So, after that, all logs will be logged in a structured manner with different levels.

**Comment by thapabishwa-plerionaut** [comment] 2023-11-08 13:06
AFAIK `log/slog` is interoperable with [logr](https://github.com/go-logr/logr), if that's the case then it should also work with `klog`.

Do you have any eta on the release?

**Comment by KimMachineGun** [comment] 2023-11-08 14:04
@thapabishwa-plerionaut
I am still determining the exact plan, but it is likely to be released either in late November or early December.

**Comment by thapabishwa** [comment] 2023-12-10 01:42
@KimMachineGun has slog compatibility been released with 0.4.0 version?

**Comment by thapabishwa** [comment] 2023-12-10 04:07
Looks like it hasn't been done just yet. I've opened PR #12 to address the slog interoperability. 
Could you please take a look and let me know about it @KimMachineGun  ?
Thanks

**Comment by KimMachineGun** [comment] 2023-12-10 05:53
@thapabishwa 
Sorry for being late.
The structured logging feature was in private testing, and I just pushed it to the [v0.5.0-pre](https://github.com/KimMachineGun/automemlimit/tree/v0.5.0-pre) branch. (Note: this is not the final version of v0.5.0) Please take a look at the code and feel free to share your feedback.

\+ I appreciate your PR, but at this time, I prefer not to add more external dependencies to this library. I think `log/slog` can handle most cases. If you have any thoughts on this, please do let me know.

**Comment by thapabishwa** [comment] 2023-12-10 15:04
Sure. Let me take a look at if this changes works for me.

**Comment by thapabishwa-plerionaut** [comment] 2023-12-12 18:36
Would you be open to updating usage instructions on the [v0.5.0-pre](https://github.com/KimMachineGun/automemlimit/tree/v0.5.0-pre) branch?

**Comment by KimMachineGun** [comment] 2023-12-14 08:14
@thapabishwa-plerionaut 
Thank you for testing! I have just released the pre-release version, and I will release v0.5.0 after a few days of testing.

I understand your concerns about updating the Go version. However, I believe that Go 1.21 was released over three months ago, and thanks to their compatibility promise, most programs should work well in Go 1.21 (in fact, they may work even better).

\+ It may be possible to provide a way to configure the logger for versions prior to 1.21, but doing so would result in additional maintenance points. In my opinion, the effort required to maintain multiple versions outweighs the benefits that it provides. 😢

**Comment by thapabishwa-plerionaut** [comment] 2023-12-29 19:10
Any new updates on `0.5.0` final release?

**Comment by thapabishwa-plerionaut** [comment] 2024-01-05 05:02
@KimMachineGun Any update on the final release of `v0.5.0`?

**Comment by KimMachineGun** [comment] 2024-01-05 06:14
@thapabishwa-plerionaut 
Sorry, the testing was done, but it had a tiny issue with its dependency. (https://github.com/containerd/cgroups/pull/321.)
Now, the issue is resolved but not released yet. And I'm waiting for the release.

If it won't be released soon, I'll tell you about the updated release plan for v0.5.0.

**Comment by thapabishwa-plerionaut** [comment] 2024-01-15 13:20
Hey @KimMachineGun , any reason why 0.5.0.pre.4 droppped support for slog?

**Comment by SuperQ** [comment] 2024-01-15 13:33
The issue with slog is it's not supported in all "supported" versions of Go. Since a lot of projects support what Go officially supports for compilers (Latest - 1), slog would force everyone to only the latest Go version.

When Go 1.22, slog can be added, since it's supported in Go >= 1.21.

Personally, I would prefer supporting logging via creating a compatible interface. This would allow whatever logging the downstream project wants to use, rather than locking to a specific logger.

**Comment by SuperQ** [comment] 2024-01-15 13:36
For example:
* https://pkg.go.dev/go.uber.org/automaxprocs@v1.5.3/maxprocs#Logger
* https://pkg.go.dev/github.com/gosnmp/gosnmp#Logger

**Comment by SuperQ** [comment] 2024-01-15 15:38
Yup, I'm really looking forward to `log/slog`, but for ecosystem compatibility, some delay is prudent.

**Comment by thapabishwa-plerionaut** [comment] 2024-01-17 03:09
If that's the case then, should we reconsider [this PR](https://github.com/KimMachineGun/automemlimit/pull/12)?

**Comment by KimMachineGun** [comment] 2024-01-18 05:31
@thapabishwa-plerionaut 
Well... I am unlikely to reconsider gologr for now because of these reasons.

> end users should be able choose their preferred Logger instance

I totally agree with you, but I don't think the library would be the best choice. As I mentioned earlier, `log/slog` would be enough.

> end users should be able to do it without having to upgrade to Go >= 1.21.

This seems reasonable for now, but after the Go 1.22 release, every Go program should use at least Go 1.21, which will be the lowest version maintained by the Go team. So, if we release this feature after the Go 1.22 release, it won't be problematic.
(The Go team maintains only the last two versions: Go 1.20/1.21 for now and Go 1.21/1.22 after the next release.)

cc. @SuperQ (FYI. could be related to your proposal https://github.com/KimMachineGun/automemlimit/issues/14)

**Comment by thapabishwa-plerionaut** [comment] 2024-01-18 16:32
> @thapabishwa-plerionaut Well... I am unlikely to reconsider gologr for now because of these reasons.
> 
> > end users should be able choose their preferred Logger instance
> 
> I totally agree with you, but I don't think the library would be the best choice. As I mentioned earlier, `log/slog` would be enough.
> 
> > end users should be able to do it without having to upgrade to Go >= 1.21.
> 
> This seems reasonable for now, but after the Go 1.22 release, every Go program should use at least Go 1.21, which will be the lowest version maintained by the Go team. So, if we release this feature after the Go 1.22 release, it won't be problematic. (The Go team maintains only the last two versions: Go 1.20/1.21 for now and Go 1.21/1.22 after the next release.)
> 
> cc. @SuperQ (FYI. could be related to your proposal #14)

Great. Looking forward to `slog`

**Comment by KimMachineGun** [comment] 2024-03-09 20:26
My apologies for the late response, I've been quite busy lately.

I've just finished a preliminary version of this feature.
As usual, we should have a few weeks for testing, possibly aiming for a late March release.

Your feedback on this pre-release version would be greatly appreciated, so feel free to leave any comments.

**Comment by KimMachineGun** [comment] 2024-04-16 13:46
Finally, v0.6.0 has been released! Please open an issue if you have any suggestions or feedback about logging.
https://github.com/KimMachineGun/automemlimit/releases/tag/v0.6.0

**Closed by KimMachineGun** 2024-04-16 13:46 UTC
Labels: enhancement
